# Generated by Django 5.2.8 on 2025-11-30 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('concluido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('refeicao', 'Refeição'), ('consulta', 'Consulta'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
